sudo: required
services: 
    - docker

before_install:
    - docker build -t jetsundev/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run jetsundev/react-test npm test -- --coverage

after_success:
    - docker build -t jetsundev/multi-client ./client
    - docker build -t jetsundev/multi-nginx ./nginx
    - docker build -t jetsundev/multi-server ./server
    - docker build -t jetsundev/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push jetsundev/multi-client
    - docker push jetsundev/multi-nginx
    - docker push jetsundev/multi-server
    - docker push jetsundev/multi-worker